import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ToastProvider } from "@/providers";
import { RoleProvider } from "@/contexts";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <RoleProvider>{children}</RoleProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
